eshop/eshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include("goods.urls", namespace="goods")),
]

eshop/goods/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# /
	url(r'^$', views.index, name="index"),
	# /ID/
	url(r'^(?P<good_id>[0-9]+)/$', views.good_info, name="good_info"),
	# /order/ID/
	url(r'^order/(?P<order_id>[0-9]+)/$', views.order_info, name="order_info"),
	# /order/create/
	url(r'^order/create/$', views.order_create, name="order_create"),
	# /hello/
	url(r'^hello/$', views.hello, name="hello"),
	# /error/MESSAGE/
	url(r'^error/(?P<message>[A-Za-z0-9\s_,.:;!-"]+)/$', views.show_error, name="show_error"),
]

eshop/goods/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Category of goods
class Category(models.Model):
	name = models.CharField(max_length=100)

# Good
class Good(models.Model):
	category = models.ForeignKey(Category)
	name = models.CharField(max_length=100)
	price = models.IntegerField(default=0)
	count = models.IntegerField(default=0)
	# get rest goods count
	def rest(self):
		result = self.count
		os = Order.objects.filter(good=self, status=0)
		for o in os:
			result -= o.count
		return result
	# get total cost of goods
	def cost(self, count):
		return self.price * count
	# create order
	def create_order(self, count):
		if self.rest() >= count:
			date = timezone.now()
			order = Order(good=self, count=count, creation_date=date)
			order.save()
			return order
		else:
			return None

# Order
class Order(models.Model):
	good = models.ForeignKey(Good)
	count = models.IntegerField(default=0)
	address = models.CharField(max_length=200)
	phone = models.CharField(max_length=20)
	creation_date = models.DateTimeField(default=timezone.now())
	take_date = models.DateTimeField(default=timezone.now())
	status = models.IntegerField(default=0)
	# take order
	def take(self):
		if self.status == 0:
			if self.good.count > self.count:
				self.good.count -= self.count
				self.status = 1
				self.take_date = timezone.now()

eshop/goods/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Category, Good, Order

def index(request):
	categories = Category.objects.order_by('-name')
	goods = Good.objects.order_by('-name')
	context = {'categories': categories, 'goods': goods}
	return render(request, 'catalog.html', context)

def good_info(request, good_id):
	good = get_object_or_404(Good, pk=good_id)
	rest = good.rest()
	return render(request, 'good.html', {'good': good, 'rest': rest})

def order_create(request):
	good_id = request.POST['good_id']
	count = request.POST['count']
	good = get_object_or_404(Good, pk=good_id)
	order = good.create_order(count)
	if order != None:
		return HttpResponseRedirect(reverse('goods:order_info', args=(order.id,)))
	else:
		return render(request, 'error.html',
		{'message': 'Cannot create order for "{1}" (x {0})'.format(count, good.name)})

def order_info(request, order_id):
	order = get_object_or_404(Question, pk=order_id)
	status = "Ready" if order.status == 0 else "Not ready"
	cost = order.good.cost(order.count)
	context = {'order': order, 'status': status, 'cost': cost}
	return render(request, 'order.html', context)

def hello(request):
	return render(request, 'error.html', {'message': 'Hello World!'})

def show_error(request, message):
	return render(request, 'error.html', {'message': message})

eshop/goods/templates/catalog.html
{% if categories %}
<H1>EShop</H1>
{% for category in categories %}
	<H2>{{category.name}}</H2>
	{% for good in goods %}
		{% if good.category.id == category.id %}
		<p><a href="{% url 'goods:good_info' 1 %}"
		>{{good.name}}</a></p>
		{% endif %}
	{% endfor %}
{% endfor %}
{% else %}
<p>No goods available.</p>
{% endif %}

eshop/goods/templates/error.html
<H1>Error</H1>

{% if message %}
<P>{{message}}</P>
{% endif %}

<a href="{% url 'goods:index' %}">Return</a>

eshop/goods/templates/good.html
<div><H2>Info</H2>
<P>Good: {{good.name}}</P>
<P>Price: {{good.price}}</P>
<P>Count: {{rest}}</P>
</div>

<div><H2>Create order</H2>
<form method="POST" action="{% url 'goods:order_create' %}">{% csrf_token %}
	<input type="hidden" name="good_id" value="{{good.id}}"/>
	<div>Count: <input type="text" name="count"/></div>
	<div><input type="submit" value="Send"/></div>
</form>
</div>

<a href="{% url 'goods:index' %}">Return</a>

eshop/goods/templates/order.html
<div><H2>Info</H2>
<P>Good: {{order.good.name}}</P>
<P>Count: {{order.count}}</P>
<P>Cost: {{cost}}</P>
<P>Status: {{status}}</P>
</div>

<a href="{% url 'goods:index' %}">Return</a>